# -*- coding: utf-8 -*-
"""Foundation of Data Science.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cut3dEmuCmbDqWSfDs9tFBQyfdqOMIoh
"""

# Importing libraries
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from scipy.stats import skew

# Loading dataset1, dataset2, and dataset3 to pandas dataframes
dataset1 = pd.read_csv('/content/dataset1.csv')
dataset2 = pd.read_csv('/content/dataset2.csv')
dataset3 = pd.read_csv('/content/dataset3.csv')

"""**Descriptive statistical analyses**"""

# Mean result for all three datasets
print("Mean for Dataset 1:")
print(dataset1.mean(), "\n")

print("Mean for Dataset 2:")
print(dataset2.mean(), "\n")

print("Mean for Dataset 3:")
print(dataset3.mean(), "\n")

# Median result for all three datasets
print("Median for Dataset 1:")
print(dataset1.median(), "\n")

print("Median for Dataset 2:")
print(dataset2.median(), "\n")

print("Median for Dataset 3:")
print(dataset3.median(), "\n")

# Mode  result for all three datasets
print("Mode for Dataset 1:")
print(dataset1.mode(), "\n")

print("Mode for Dataset 2:")
print(dataset2.mode(), "\n")

print("Mode for Dataset 3:")
print(dataset3.mode(), "\n")

# Standard deviation for all three dataset
print("Standard Deviation for Dataset 1:")
print(dataset1.std(), "\n")

print("Standard Deviation for Dataset 2:")
print(dataset2.std(), "\n")

print("Standard Deviation for Dataset 3:")
print(dataset3.std(), "\n")

# Variance for all three datasets
print("Variance for Dataset 1:")
print(dataset1.var(), "\n")

print("Variance for Dataset 2:")
print(dataset2.var(), "\n")

print("Variance for Dataset 3:")
print(dataset3.var(), "\n")

# Skewness for 3 datasets
print("Skewness for Dataset 1:")
print(dataset1.skew(), "\n")

print("Skewness for Dataset 2:")
print(dataset2.skew(), "\n")

print("Skewness for Dataset 3:")
print(dataset3.skew(), "\n")

# Ploting histograms of 3 datasets
fig, axs = plt.subplots(3, 3, figsize=(15, 10))
fig.suptitle('Histograms for all datasets: Dataset 1, Dataset 2 and Dataset 3')

# histograms of dataset 1
axs[0, 0].hist(dataset1['gender'], bins=2, color='lightblue', edgecolor='black')
axs[0, 0].set_title('Dataset 1: Gender')

axs[0, 1].hist(dataset1['minority'], bins=2, color='lightgreen', edgecolor='black')
axs[0, 1].set_title('Dataset 1: Minority')

axs[0, 2].hist(dataset1['deprived'], bins=2, color='lightcoral', edgecolor='black')
axs[0, 2].set_title('Dataset 1: Deprived')

#  histograms of dataset 2
axs[1, 0].hist(dataset2['C_we'], bins=10, color='lightblue', edgecolor='black')
axs[1, 0].set_title('Dataset 2: Computer (Weekends)')

axs[1, 1].hist(dataset2['G_we'], bins=10, color='lightgreen', edgecolor='black')
axs[1, 1].set_title('Dataset 2: Games (Weekends)')

axs[1, 2].hist(dataset2['S_we'], bins=10, color='lightcoral', edgecolor='black')
axs[1, 2].set_title('Dataset 2: Smartphone (Weekends)')

#  histograms of dataset 3
axs[2, 0].hist(dataset3['Optm'], bins=5, color='lightblue', edgecolor='black')
axs[2, 0].set_title('Dataset 3: Optimistic')

axs[2, 1].hist(dataset3['Usef'], bins=5, color='lightgreen', edgecolor='black')
axs[2, 1].set_title('Dataset 3: Useful')

axs[2, 2].hist(dataset3['Relx'], bins=5, color='lightcoral', edgecolor='black')
axs[2, 2].set_title('Dataset 3: Relaxed')

plt.tight_layout()
plt.show()

# summary of Descriptive statistic for all three datasets
print(" summary of Descriptive Statistics for Dataset 1:")
print(dataset1.describe(), "\n")

print("summary of Descriptive Statistics for Dataset 2:")
print(dataset2.describe(), "\n")

print("summary of Descriptive Statistics for Dataset 3:")
print(dataset3.describe(), "\n")